name: Register interest
description: Let us know you're interested in the Property Management App
title: "Interest: "
labels: ["interest"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Ada Lovelace
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: What excites you about this idea?
    validations:
      required: true
